services:
  php:
    build:
      context: ./infra/php
      dockerfile: Dockerfile
      args:
        - USER_UID=${USER_UID:-1000}
        - LOCAL_PORT=${LOCAL_PORT:-8080}
    volumes:
      - ./src:/home/devel/workspace
    environment:
      APACHE_RUN_USER: "devel"
      APACHE_RUN_GROUP: "devel"
    ports:
      - '${LOCAL_PORT:-8080}:80'
